name: alexnet_rafael
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  - pyyaml
  - pandas
  - tensorboard
  - pip:
      - -e .
      - pytest
      - torchmetrics==1.9.0
      - torchinfo
      - fvcore
      - wandb
      - kagglehub
      - pycocotools==2.0.11
